INSERT INTO feature_films(id, image, title, release_year, country, director, main_roles, genres, box_office,
                          brief_description, certificate, runtime, tags, trailer) VALUES
(
 'cbad028d-2180-4e9d-b217-17d2c26a79e1',
 '7455db87-35f3-4818-8b87-6856fd0488b1.jpg',
 'The Shawshank Redemption',
 1994,
 'USA',
 'Frank Darabont',
 'Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler, Clancy Brown, Gil Bellows, Mark Rolston, James Whitmore',
 'Drama',
 59840000,
 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
 '16+',
 '02:22',
 'freedom, hope, prison, escape, system',
 'https://www.youtube.com/embed/NmzuHjWmXOc'
 ),
(
 '4b0d6d45-b489-4521-bf6c-a25b529fa2ad',
 '4ba3fb20-80fa-4db5-89ba-e2ac93e60ff2.jpg',
 'The Green Mile',
 1999,
 'USA',
 'Frank Darabont',
 'Tom Hanks, David Morse, Bonnie Hunt, Michael Clarke Duncan, James Cromwell, Michael Jeter, Graham Greene',
 'Crime, Drama, Fantasy, Mystery',
 286801000,
 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
 '16+',
 '03:09',
 'good, hope, miracle, prison, struggle',
 'https://www.youtube.com/embed/Ki4haFrqSrw'
 ),
(
 '99a96677-7e62-4d1d-91e4-841312945061',
 '34ad62e2-2125-41d1-93f7-5dfcaccd65b8.jpg',
 'Forrest Gump',
 1994,
 'USA',
 'Robert Zemeckis',
 'Tom Hanks, Rebecca Williams, Sally Field, Michael Conner Humphreys, Harold G. Herthum, George Kelly, Bob Penny',
 'Drama, Romance',
 677386686,
 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75.',
 '12+',
 '02:22',
 'development, kind, military, naive, president, service',
 'https://www.youtube.com/embed/XHhAG-YLdk8'
 ),
(
 '8152c47a-91b5-4a19-9e14-5918de7cf13c',
 '2bfb631e-eb95-4086-a137-3f6cb6b65b80.jpg',
 'Schindler''s List',
 1993,
 'USA',
 'Steven Spielberg',
 'Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall, Jonathan Sagall, Embeth Davidtz, Malgorzata Gebel',
 'Biography, Drama, History',
 321265768,
 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
 '16+',
 '03:15',
 'World War II, holocaust, Auschwitz concentration camp, humanism, Poland',
 'https://www.youtube.com/embed/gG22XNhtnoY'
),
(
 'b31f4106-17ab-4170-876e-9fb5c9927f4c',
 '35db55e6-a060-43e6-804f-aa225d641086.jpg',
 'Intouchables',
 2011,
 'France',
 'Olivier Nakache, Éric Toledano',
 'François Cluzet, Omar Sy, Anne Le Ny, Audrey Fleurot, Joséphine de Meaux, Clotilde Mollet, Alba Gaïa Bellugi',
 'Biography, Comedy, Drama',
 416389690,
 'After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.',
 '16+',
 '01:52',
 'friendship, social worker, wheelchair-bound, rich, poor',
 'https://www.youtube.com/embed/oK5hMNxqsFA'
),
(
 '853f5f63-fe71-4bfe-8051-2cc79f0789bf',
 '64c90fc0-fe9e-4751-aed7-ca553516e3a3.jpg',
 'Léon',
 1994,
 'France',
 'Luc Besson',
 'Jean Reno, Gary Oldman, Natalie Portman, Danny Aiello, Peter Appel, Willi One Blood, Don Creech',
 'Action, Crime, Drama, Thriller',
 45501238,
 'Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. Léon and Mathilda form an unusual relationship, as she becomes his protégée and learns the assassin''s trade.',
 '16+',
 '02:13',
 'professional assassin, relationship, protégée, neighbor',
 'https://www.youtube.com/embed/jawVxq1Iyl0'
),
(
 'b54771b6-7895-405b-b4fd-8faf5d0524ff',
 '8731ff97-b79b-47f5-909b-7a4fcecb8959.jpg',
 'Inception',
 2010,
 'USA, UK',
 'Christopher Nolan',
 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy, Ken Watanabe, Dileep Rao, Cillian Murphy',
 'Action, Adventure, Sci-Fi, Thriller',
 825532764,
 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
 '12+',
 '02:28',
 'dream, subconscious, ambiguous ending, thief, psycho thriller',
 'https://www.youtube.com/embed/YoHD9XEInc0'
),
(
 '4c748995-89ef-4b59-bb91-9ad59333ecc0',
 '085bcfdc-8d40-4465-8903-44245704753d.jpg',
 'Fight Club',
 1999,
 'USA, Germany',
 'David Fincher',
 'Brad Pitt, Edward Norton, Meat Loaf, Zach Grenier, Richmond Arquette, David Andrews, George Maguire',
 'Drama',
 100853753,
 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',
 '18+',
 '02:19',
 'chronic insomnia, office worker, fake attendee, support group, underground fight club',
 'https://www.youtube.com/embed/qtRKdVHc-cE'
),
(
 '9e004728-061c-406c-be27-7ec1f4e2dc6b',
 '4256a9a6-558b-461a-b9fe-151067871d40.jpg',
 'La vita è bella',
 1997,
 'Italy',
 'Roberto Benigni',
 'Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini, Giustino Durano, Sergio Bini Bustric, Marisa Paredes, Horst Buchholz',
 'Comedy, Drama, Romance, War',
 229163264,
 'When an open-minded Jewish librarian and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.',
 '12+',
 '01:56',
 'jewish, schoolteacher, world war two, nazi occupation, tank',
 'https://www.youtube.com/embed/pAYEQP8gx3w'
),
(
 '59429958-97c3-4f74-892b-c2ce86fa68ef',
 'e08448d8-651d-46db-9c79-8b269986a61d.jpg',
 'Knockin'' on Heaven''s Door',
 1997,
 'Germany',
 'Thomas Jahn',
 'Til Schweiger, Jan Josef Liefers, Thierry van Werveke, Moritz Bleibtreu, Huub Stapel, Leonard Lansink, Ralph Herforth',
 'Action, Crime, Comedy, Drama',
 5710,
 'Two young men, Martin and Rudi, both suffering from terminal cancer, get to know each other in a hospital room. They drown their desperation in Tequila and decide to take one last trip to the sea. Drunk and still in pajamas they steal the first fancy car they find, a 60''s Mercedes convertible. The car happens to belong to a bunch of gangsters, which immediately start to chase it, since it contains more than the pistol Martin finds in the glove box.',
 '16+',
 '01:27',
 'acquaintance, friendship, incurable disease, last trip to the sea, dream',
 'https://www.youtube.com/embed/IzMIoaISKb8'
);

INSERT INTO documentary_films(id, image, title, release_year, country, director, category, brief_description,
                              certificate, runtime, tags, trailer) VALUES
(
 'f8ccc193-e136-4e5b-a95e-5f887ff02df9',
 'b8d7ca32-631f-48ba-a9e9-a1b96e0b8949.jpg',
 'The Brain with Dr. David Eagleman',
 2015,
 'USA',
 'Glenn Barden',
 'Research',
 'Six one-hour episodes that tell the story of the inner workings of the brain and take viewers on a visually spectacular journey into why they feel and think the things they do.',
 '12+',
 '6 episodes for 1 hour',
 'science, brain, reflexes, consciousness, mind',
 'https://www.youtube.com/embed/cTl2Odxgr54'
),
(
 'fed1c34a-71a6-497f-b4cc-2ad0c443df95',
 'e971c79f-7044-4ad8-80cb-0fc0a94159d9.jpg',
 'Apollo 11',
 2019,
 'USA',
 'Todd Douglas Miller',
 'Chronicle',
 'A look at the Apollo 11 mission to land on the moon led by commander Neil Armstrong and pilots Buzz Aldrin and Michael Collins.',
 '0+',
 '01:23',
 'space, Neil Armstrong, Moon, mission, Earth',
 'https://www.youtube.com/embed/RwNkfLxLG8c'
),
(
 'd4991c9b-c759-485c-8253-cb14c3a99a0d',
 'cbbbcd77-8938-48a3-b7ca-67326741c5ce.jpg',
 'Meeting Gorbachev',
 2018,
 'USA',
 'Werner Herzog',
 'Chronicle, Propaganda(history)',
 'The life of Mikhail Gorbachev, the eighth and final President of the Soviet Union in chronological order.',
 '12+',
 '01:30',
 'history, USSR, breakup, cold war, GDR(German Democratic Republic)',
 'https://www.youtube.com/embed/c18V6Y3HL38'
),
(
 '01317c4b-5b71-4dc8-8ff9-6cb1294f625c',
 '594a6314-6992-4822-af1a-9fe1b278f5ff.jpg',
 'Senna',
 2010,
 'UK, France, USA',
 'Asif Kapadia',
 'Biography, Sport',
 'A documentary on Brazilian Formula One racing driver Ayrton Senna, who won the F1 world championship three times before his death at age 34.',
 '16+',
 '02:42',
 'Formula One racing, Ayrton Senna, F1 world championship, man with a capital letter, legend',
 'https://www.youtube.com/embed/5sXAN05zW5o'
),
(
 '78675062-928a-4dba-9780-40d86dfcc200',
 '62957c8f-2bad-4966-91d6-d5bac564f0b6.jpg',
 'Earthlings',
 2005,
 'USA',
 'Shaun Monson',
 'Documentary Horror',
 'Using hidden cameras and never-before-seen footage, Earthlings chronicles the day-to-day practices of the largest industries in the world, all of which rely entirely on animals for profit.',
 '18+',
 '01:35',
 'animals in distress, pain, animal cruelty, violence, animal abuse',
 'https://www.youtube.com/embed/7zawxANsM_I'
),
(
 '81a59c53-3a11-48b7-aa37-03d595f54cce',
 'ffa7dcf7-f0a1-457f-8453-869dcfa5f92b.jpg',
 'Océans',
 2009,
 'France, Switzerland, Spain and others',
 'Jacques Perrin, Jacques Cluzaud',
 'Nature, Drama',
 'An ecological drama/documentary, filmed throughout the globe. Part thriller, part meditation on the vanishing wonders of the sub-aquatic world.',
 '0+',
 '01:44',
 'pufferfish, sea turtle, habitat, shark, marine life',
 'https://www.youtube.com/embed/uXLbQrK6cXw'
),
(
 '4742148c-204f-4971-880d-00abafcdb2f0',
 '18834974-108d-4bfe-85b2-d5ea3c655cae.jpg',
 'Human',
 2015,
 'France',
 'Yann Arthus-Bertrand',
 'Humankind',
 'A collection of stories about and images of our world, offering an immersion to the core of what it means to be human.',
 '18+',
 '02:14',
 'human, humankind, relationship, future, lessons of the past',
 'https://www.youtube.com/embed/Ky0LDCtXeDc'
),
(
 'f5afb1c6-9e03-4956-9b9e-65f61e72b3f7',
 'ecca75c7-5963-4ee2-8533-347a9b8f3a07.jpg',
 'Samsara',
 2011,
 'USA, Indonesia, Singapore and others',
 'Ron Fricke',
 'Humankind, Music',
 'Filmed over nearly five years in twenty-five countries on five continents, and shot on seventy-millimetre film, Samsara transports us to the varied worlds of sacred grounds, disaster zones, industrial complexes, and natural wonders.',
 '12+',
 '01:42',
 'subway, islam, shanghai china, trippy, yellowstone national park',
 'https://www.youtube.com/embed/HCkEILshUyU'
),
(
 '8a42dc6d-ff8a-4b30-a6ad-c6cd8c5f4112',
 '7e7c863b-f1a3-4617-8693-4f3defd71073.jpg',
 'An Inconvenient Truth',
 2006,
 'USA',
 'Davis Guggenheim',
 'Pollution',
 'Filmmaker Davis Guggenheim follows Al Gore on the lecture circuit, as the former presidential candidate campaigns to raise public awareness of the dangers of global warming and calls for immediate action to curb its destructive effects on the environment.',
 '0+',
 '01:36',
 'climate, global warming, global climate change, climate change, warmth',
 'https://www.youtube.com/embed/Bu6SE5TYrCM'
),
(
 'e841e9ab-69e8-4493-be3d-83a136f7257e',
 'be977c35-28e5-4a3f-8925-f15fa770bcdc.jpg',
 'Baraka',
 1992,
 'USA',
 'Ron Fricke',
 'Humankind, Music',
 'A collection of expertly photographed scenes of human life and religion.',
 '12+',
 '01:36',
 'human nature, environmental education, world culture, working conditions, environment',
 'https://www.youtube.com/embed/ZSfFHxyYJJA'
);

INSERT INTO cartoons(id, image, title, release_year, country, method_of_creation, director, genres, brief_description,
                 certificate, duration, runtime, tags, trailer) VALUES
(
 '9c004bcb-5e7b-48d3-9fb8-39f3261f0941',
 '8df02e47-653e-46b6-9f0e-dce126a38368.jpg',
 'The Secret Life of Pets',
 2016,
 'Japan, USA, France',
 'CGI-animation',
 'Chris Renaud',
 'adventure, comedy, family',
 'The quiet life of a terrier named Max is upended when his owner takes in Duke, a stray whom Max instantly dislikes.',
 '6+',
 'full-length',
 '01:27',
 'pets, relationship, dogs, homecoming, secret life',
 'https://www.youtube.com/embed/-yPuWcCykNk'
),
(
 'e50c366c-9da7-42b6-a537-f44efcc634d2',
 '7c73837f-7a97-4429-9eb0-a5e6497ef2da.jpg',
 '5 centimeters per second',
 2007,
 'Japan',
 'Draw plasticine',
 'Makoto Shinkai',
 'drama, romance',
 'Told in three interconnected segments, we follow a young man named Takaki through his life as cruel winters, cold technology, and finally, adult obligations and responsibility converge to test the delicate petals of love.',
 '12+',
 'short-length',
 '01:03',
 'three stories, romance, Japan, relationship, love',
 'https://www.youtube.com/embed/wdM7athAem0'
),
(
 'd0f1f200-a19a-40e4-8c78-54b99332a388',
 'f6e2b07f-dbf5-4659-ae8f-aeac83b7fa9c.jpg',
 'Shaun the Sheep Movie',
 2015,
 'UK, France, USA',
 'Plasticine',
 'Mark Burton',
 'adventure, Comedy, family, fantasy',
 'When Shaun decides to take the day off and have some fun, he gets a little more action than he bargained for. A mix up with the Farmer, a caravan and a very steep hill lead them all to the Big City and it''s up to Shaun and the flock to return everyone safely to the green grass of home.',
 '0+',
 'full-length',
 '01:21',
 'sheep, dogs, farm, mutual assistance, rescue',
 'https://www.youtube.com/embed/0_4vs0nCCUI'
),
(
 '18132db7-daa8-4820-968a-a694a7a9bb99',
 'a3f67e33-bb60-4bfd-b541-f0d697cfab8b.jpg',
 'The Lion King',
 1994,
 'USA',
 'Computer animation',
 'Roger Allers, Rob Minkoff',
 'Adventure, Drama, Family, Musical',
 'A Lion cub crown prince is tricked by a treacherous uncle into thinking he caused his father''s death and flees into exile in despair, only to learn in adulthood his identity and his responsibilities.',
 '0+',
 'full-length',
 '01:28',
 'king, lion, unnecessary guilt, scar, prince',
 'https://www.youtube.com/embed/eHcZlPpNt0Q'
),
(
 'f40cfa88-d351-4ffd-912f-283f91a19b45',
 '0769c0f4-4f2c-4739-a3b8-fcbe439f80d2.jpg',
 'WALL·E',
 2008,
 'USA',
 'Computer animation',
 'Andrew Stanton',
 'Adventure, Family, Sci-Fi',
 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.',
 '0+',
 'full-length',
 '01:38',
 'robot, obesity, recycling robot, adrift in space, cgi animation',
 'https://www.youtube.com/embed/CZ1CATNbXg0'
),
(
 'c62ab119-2256-463e-a464-d90e9add1683',
 'a6e80817-5b4e-4af3-82bd-eaeb2604eabd.jpg',
 'Coco',
 2017,
 'USA',
 'Computer animation',
 'Lee Unkrich, Adrian Molina',
 'Adventure, Comedy, Family, Fantasy, Music, Mystery',
 'Aspiring musician Miguel, confronted with his family''s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.',
 '12+',
 'full-length',
 '01:45',
 'mexico, death, afterlife, day of the dead, ban on music',
 'https://www.youtube.com/embed/Ga6RYejo6Hk'
),
(
 'ab700088-d3f2-4521-b957-53c377074553',
 'eec79b6f-292a-41cd-90bc-2fcdedc9123f.jpg',
 'Partly Cloudy',
 2009,
 'USA',
 'Computer animation',
 'Peter Sohn',
 'Comedy, Family, Fantasy',
 'Babies both human and animal are created up in the stratosphere, by the clouds themselves. One cloud specializes in "dangerous" babies, creating a challenge for his loyal stork that has to deliver them.',
 '0+',
 'short-length',
 '00:06',
 'baby, stork, cloud, porcupine, delivery stork',
 'https://www.youtube.com/embed/gaCfY57LIkA'
),
(
 '3855192f-cb46-4b51-9183-8d40e6109f73',
 'cbaafc87-c245-459f-a602-30bdcca27686.jpg',
 'Sen to Chihiro no kamikakushi',
 2001,
 'Japan',
 'Computer animation',
 'Hayao Miyazaki, Kirk Wise',
 'Adventure, Family, Fantasy, Mystery',
 'During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
 '12+',
 'full-length',
 '02:05',
 'spirit, bathhouse, anime, spirit world, studio ghibli',
 'https://www.youtube.com/embed/ByXuk9QqQkk'
),
(
 '2f96c8c2-0991-4216-87bc-ff2c56539ee0',
 'c8da97b1-6bb6-4ae3-9889-11d5278357f0.jpg',
 'Zootopia',
 2016,
 'USA',
 'Computer animation',
 'Byron Howard, Rich Moore',
 'Adventure, Comedy, Crime, Family, Mystery',
 'In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy.',
 '6+',
 'full-length',
 '01:48',
 'fox, con artist, police, anthropomorphic animal, rabbit',
 'https://www.youtube.com/embed/yCOPJi0Urq4'
),
(
 '22a26164-becc-4407-a1f9-14d88a7e1517',
 '9a77d419-25e6-46fa-b14c-78587a5c18f4.jpg',
 'Inside Out',
 2015,
 'USA',
 'Computer animation',
 'Pete Docter, Ronnie Del Carmen',
 'Comedy, Drama, Family, Fantasy',
 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.',
 '6+',
 'full-length',
 '01:35',
 'joy, sadness, memory, anger, running away',
 'https://www.youtube.com/embed/seMwpP0yeu4'
)